apiVersion: v1
kind: Template
metadata:
  name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
labels:
  template: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
metadata:
  annotations:
    description: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    tags: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
  name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
objects:

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME} http port
    labels:
      app: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
      deploymentconfig: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    tls:
      termination: edge

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
  spec:
    replicas: 1
    selector:
      app: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
      deploymentconfig: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
          deploymentconfig: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
      spec:
        containers:
        - image: ${CI_REGISTRY_IMAGE}:${BUILD_VERSION}
          imagePullPolicy: Always
          name: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
  status: {}
